version: "2"
services:
  regtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/node-only"
    container_name: node-only
    ports:
      - "18445:18332"
    stdin_open: true
    tty: true
    privileged: true
    command: bash -c "doichaind -regtest"

  mainnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/node-only"
    container_name: node-only
    ports:
      - "8338:8339"
    stdin_open: true
    tty: true
    privileged: true
    command: bash -c "doichaind"

  testnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/node-only"
    container_name: node-only
    ports:
      - "18338:18339"
    stdin_open: true
    tty: true
    privileged: true
    command: bash -c "doichaind -testnet"





# Start with docker-compose run regtest bash



