version: "2"
services:
  regtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: "doichain/node-only"
    container_name: regtest
    ports:
      - "18445:18332"
    stdin_open: true
    tty: true
    privileged: true
    environment:
      DOCKER_ON_RUN: doichaind -regtest

  # mainnet:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: "doichain/node-only"
  #   container_name: mainnet
  #   ports:
  #     - "8338:8339"
  #   stdin_open: true
  #   tty: true
  #   privileged: true
  #   environment:
  #     DOCKER_ON_RUN: doichaind

  # testnet:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: "doichain/node-only"
  #   container_name: testnet
  #   ports:
  #     - "18338:18339"
  #   stdin_open: true
  #   tty: true
  #   privileged: true
  #   environment:
  #     DOCKER_ON_RUN: doichaind -testnet





