version: "2"
services:
  regtest:
    build: ./Dockerfile
    image: "doichain/node-only"
    container_name: node-only
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: bash -c "doichaind -regtest"

# Start with docker-compose run regtest bash



